stages:
  - build
  - deploy

build:
  stage: build
  image: registry.gitlab.com/pages/hugo:latest
  script:
      - hugo --baseURL=https://asc-docs.s3-website-us-west-2.amazonaws.com/foundationaldataproducts
  artifacts:
    paths:
      - public

deploy:
  stage: deploy
  image: xueshanf/awscli:latest
  only: 
    - main
  script:
      - aws s3 sync public s3://asc-docs/foundationaldataproducts
